# Generated by Django 5.2.9 on 2026-06-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('original_name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('FOLDER', 'Folder'), ('FILE', 'File')], default='FOLDER', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filesystem.node')),
            ],
            options={
                'verbose_name': 'Nodes',
                'verbose_name_plural': 'Nodes',
                'db_table': 'nodes',
            },
        ),
    ]
