# Generated by Django 5.2.9 on 2026-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
